name: CI

on:
  push:
    branches: [development, master]
  pull_request:
    branches: [development, master]
  workflow_dispatch:

permissions:
  contents: read
  checks: write

jobs:
  ci:
    uses: AtyaLibraries/github-workflows/.github/workflows/dotnet-package-ci.yml@v1
    with:
      solution: ./Validation.sln
      test-project: ./tests/Validation.UnitTests/Validation.UnitTests.csproj
      package-project: ./src/Validation/Validation.csproj
      fail-on-coverage: true
      coverage-line-min: 90
      coverage-branch-min: 80
