name: Dependency Review

on:
  pull_request:
    branches: [development, master]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  dependency-review:
    uses: AtyaLibraries/github-workflows/.github/workflows/dependency-review.yml@v1
